### ISSUE TITLE
Add list of requirements

### ISSUE THREAD

**Issue by JeanBilheux** [neutronimaging/ToFImaging#61]
We need to have a *requirements.txt*, and a *requirements_dev.txt* that will list the python packages needed to be able to use that library.

**Comment by matteobsu** [comment]
Thanks for the feedback.
I will add this to the next release.

**Comment by JeanBilheux** [comment]
Well I'm working on a branch that will add those changes. I will then create a Pull Requests to allow you to review the changes, accept or reject them and then merge it back to master

**Comment by matteobsu** [comment]
Jean, apparently we had the same idea :)
You can review or propose changes in the pull request.

**Comment by JeanBilheux** [comment]
I just sent you an invite to our slack channel to make the communication easier
