### ISSUE TITLE
prepare project to library package convention

### ISSUE THREAD

**Issue by JeanBilheux** [neutronimaging/ToFImaging#65]
This steps will make the transition to a pip module easier.

Work will be done in branch jean_python_packaging

**Comment by anderskaestner** [comment]
Can you please use our convention when you create new branches? issue<Number>_shortdescription, In the case of the branch you just started it would be issue65_pythonPackaging.

**Comment by JeanBilheux** [comment]
I knew you gonna say that and I thought about that just after creating the branch. :-).
I promise I will from now on!

sorry about that
